# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MagscopeLinux.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1303, 850)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font-family: Arial;")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameslider = QtWidgets.QProgressBar(self.centralwidget)
        self.frameslider.setGeometry(QtCore.QRect(12, 856, 1071, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameslider.sizePolicy().hasHeightForWidth())
        self.frameslider.setSizePolicy(sizePolicy)
        self.frameslider.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frameslider.setStyleSheet("    QProgressBar {\n"
"        border: 2px solid rgba(33, 37, 43, 180);\n"
"        border-radius: 5px;\n"
"        text-align: center;\n"
"        background-color: rgba(33, 37, 43, 180);\n"
"        color: black;\n"
"    }\n"
"    QProgressBar::chunk {\n"
"        background-color: #FFD700;\n"
"    }")
        self.frameslider.setMinimum(0)
        self.frameslider.setMaximum(100)
        self.frameslider.setProperty("value", 0)
        self.frameslider.setObjectName("frameslider")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(12, 888, 971, 100))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.plainTextEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.plainTextEdit.setMouseTracking(True)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.VideoFeedLabel = QtWidgets.QLabel(self.centralwidget)
        self.VideoFeedLabel.setGeometry(QtCore.QRect(12, 12, 1371, 821))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoFeedLabel.sizePolicy().hasHeightForWidth())
        self.VideoFeedLabel.setSizePolicy(sizePolicy)
        self.VideoFeedLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.VideoFeedLabel.setMouseTracking(True)
        self.VideoFeedLabel.setStyleSheet("background-color: rgb(0,0,0); border:2px solid rgb(255, 0, 0); ")
        self.VideoFeedLabel.setText("")
        self.VideoFeedLabel.setScaledContents(False)
        self.VideoFeedLabel.setObjectName("VideoFeedLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(275, 823))
        self.dockWidget.setMaximumSize(QtCore.QSize(524287, 1000))
        self.dockWidget.setFloating(False)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("font-size: 15pt; font: Arial;")
        self.tabWidget.setObjectName("tabWidget")
        self.tracking_tab = QtWidgets.QWidget()
        self.tracking_tab.setObjectName("tracking_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tracking_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.choosevideobutton = QtWidgets.QPushButton(self.tracking_tab)
        self.choosevideobutton.setStyleSheet("     QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"            \n"
"            \n"
"            }")
        self.choosevideobutton.setObjectName("choosevideobutton")
        self.gridLayout.addWidget(self.choosevideobutton, 0, 0, 1, 1)
        self.trackbutton = QtWidgets.QPushButton(self.tracking_tab)
        self.trackbutton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.trackbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 255);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 255);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(0, 255, 0);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.trackbutton.setCheckable(True)
        self.trackbutton.setObjectName("trackbutton")
        self.gridLayout.addWidget(self.trackbutton, 1, 0, 1, 1)
        self.framelabel = QtWidgets.QLabel(self.tracking_tab)
        self.framelabel.setObjectName("framelabel")
        self.gridLayout.addWidget(self.framelabel, 2, 0, 1, 1)
        self.pausebutton = QtWidgets.QPushButton(self.tracking_tab)
        self.pausebutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(150, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(150, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 150);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 255);\n"
"                font: bold 12px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(255, 0, 0);\n"
"                padding-left: 2px;\n"
"                padding-top: 2px;\n"
"            }")
        self.pausebutton.setCheckable(True)
        self.pausebutton.setObjectName("pausebutton")
        self.gridLayout.addWidget(self.pausebutton, 3, 0, 1, 1)
        self.leftbutton = QtWidgets.QToolButton(self.tracking_tab)
        self.leftbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:pressed {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.leftbutton.setAutoRepeat(True)
        self.leftbutton.setAutoRepeatInterval(1)
        self.leftbutton.setArrowType(QtCore.Qt.LeftArrow)
        self.leftbutton.setObjectName("leftbutton")
        self.gridLayout.addWidget(self.leftbutton, 4, 0, 1, 1)
        self.rightbutton = QtWidgets.QToolButton(self.tracking_tab)
        self.rightbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:pressed {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.rightbutton.setAutoRepeat(True)
        self.rightbutton.setAutoRepeatInterval(1)
        self.rightbutton.setArrowType(QtCore.Qt.RightArrow)
        self.rightbutton.setObjectName("rightbutton")
        self.gridLayout.addWidget(self.rightbutton, 4, 1, 1, 1)
        self.maskbutton = QtWidgets.QPushButton(self.tracking_tab)
        self.maskbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-style: inset;\n"
"              border-color: rgb(0, 255, 0);\n"
"            }")
        self.maskbutton.setCheckable(True)
        self.maskbutton.setChecked(False)
        self.maskbutton.setObjectName("maskbutton")
        self.gridLayout.addWidget(self.maskbutton, 5, 0, 1, 1)
        self.maskinvert_checkBox = QtWidgets.QCheckBox(self.tracking_tab)
        self.maskinvert_checkBox.setChecked(True)
        self.maskinvert_checkBox.setObjectName("maskinvert_checkBox")
        self.gridLayout.addWidget(self.maskinvert_checkBox, 6, 0, 1, 2)
        self.maskthreshlabel = QtWidgets.QLabel(self.tracking_tab)
        self.maskthreshlabel.setObjectName("maskthreshlabel")
        self.gridLayout.addWidget(self.maskthreshlabel, 7, 0, 1, 1)
        self.maskthreshbox = QtWidgets.QSpinBox(self.tracking_tab)
        self.maskthreshbox.setMaximum(255)
        self.maskthreshbox.setProperty("value", 128)
        self.maskthreshbox.setObjectName("maskthreshbox")
        self.gridLayout.addWidget(self.maskthreshbox, 7, 2, 1, 1)
        self.maskdilationlabel = QtWidgets.QLabel(self.tracking_tab)
        self.maskdilationlabel.setObjectName("maskdilationlabel")
        self.gridLayout.addWidget(self.maskdilationlabel, 8, 0, 1, 1)
        self.maskdilationbox = QtWidgets.QSpinBox(self.tracking_tab)
        self.maskdilationbox.setMaximum(40)
        self.maskdilationbox.setObjectName("maskdilationbox")
        self.gridLayout.addWidget(self.maskdilationbox, 8, 2, 1, 1)
        self.croplengthlabel = QtWidgets.QLabel(self.tracking_tab)
        self.croplengthlabel.setObjectName("croplengthlabel")
        self.gridLayout.addWidget(self.croplengthlabel, 9, 0, 1, 1)
        self.croplengthbox = QtWidgets.QSpinBox(self.tracking_tab)
        self.croplengthbox.setMinimum(5)
        self.croplengthbox.setMaximum(300)
        self.croplengthbox.setProperty("value", 40)
        self.croplengthbox.setDisplayIntegerBase(10)
        self.croplengthbox.setObjectName("croplengthbox")
        self.gridLayout.addWidget(self.croplengthbox, 9, 2, 1, 1)
        self.savedatabutton = QtWidgets.QPushButton(self.tracking_tab)
        self.savedatabutton.setStyleSheet("QPushButton {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(255, 255, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 255, 100);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(255, 255, 200);\n"
"                color: rgb(0, 0, 0);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: red;\n"
"                border: 2px solid red;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"                border-style: inset;\n"
"                }")
        self.savedatabutton.setCheckable(True)
        self.savedatabutton.setObjectName("savedatabutton")
        self.gridLayout.addWidget(self.savedatabutton, 10, 0, 1, 1)
        self.recordbutton = QtWidgets.QPushButton(self.tracking_tab)
        self.recordbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.recordbutton.setCheckable(True)
        self.recordbutton.setObjectName("recordbutton")
        self.gridLayout.addWidget(self.recordbutton, 10, 1, 1, 2)
        self.robotarealabel = QtWidgets.QLabel(self.tracking_tab)
        self.robotarealabel.setObjectName("robotarealabel")
        self.gridLayout.addWidget(self.robotarealabel, 11, 0, 1, 1)
        self.robotvelocitylabel = QtWidgets.QLabel(self.tracking_tab)
        self.robotvelocitylabel.setObjectName("robotvelocitylabel")
        self.gridLayout.addWidget(self.robotvelocitylabel, 12, 0, 1, 1)
        self.robotblurlabel = QtWidgets.QLabel(self.tracking_tab)
        self.robotblurlabel.setObjectName("robotblurlabel")
        self.gridLayout.addWidget(self.robotblurlabel, 13, 0, 1, 1)
        self.CroppedVideoFeedLabel = QtWidgets.QLabel(self.tracking_tab)
        self.CroppedVideoFeedLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.CroppedVideoFeedLabel.setMaximumSize(QtCore.QSize(400, 400))
        self.CroppedVideoFeedLabel.setStyleSheet("background-color: rgb(0,0,0); border:2px solid rgb(255, 0, 0); ")
        self.CroppedVideoFeedLabel.setText("")
        self.CroppedVideoFeedLabel.setObjectName("CroppedVideoFeedLabel")
        self.gridLayout.addWidget(self.CroppedVideoFeedLabel, 14, 0, 1, 3)
        self.resetdefaultbutton = QtWidgets.QPushButton(self.tracking_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.resetdefaultbutton.setFont(font)
        self.resetdefaultbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(100, 100, 100);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(100, 100, 100);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(200, 200, 200);\n"
"                color: rgb(0, 0, 0);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(200, 200, 200);\n"
"         \n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"                border-style: inset;\n"
"                }")
        self.resetdefaultbutton.setObjectName("resetdefaultbutton")
        self.gridLayout.addWidget(self.resetdefaultbutton, 15, 0, 1, 1)
        self.tabWidget.addTab(self.tracking_tab, "")
        self.control_tab = QtWidgets.QWidget()
        self.control_tab.setObjectName("control_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.control_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.controlbutton = QtWidgets.QPushButton(self.control_tab)
        self.controlbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 255);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 255);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(0, 255, 0);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.controlbutton.setCheckable(True)
        self.controlbutton.setObjectName("controlbutton")
        self.gridLayout_3.addWidget(self.controlbutton, 0, 0, 1, 4)
        self.rollradio = QtWidgets.QRadioButton(self.control_tab)
        self.rollradio.setChecked(True)
        self.rollradio.setObjectName("rollradio")
        self.gridLayout_3.addWidget(self.rollradio, 1, 0, 1, 1)
        self.swimradio = QtWidgets.QRadioButton(self.control_tab)
        self.swimradio.setObjectName("swimradio")
        self.gridLayout_3.addWidget(self.swimradio, 1, 1, 1, 2)
        self.orientradio = QtWidgets.QRadioButton(self.control_tab)
        self.orientradio.setObjectName("orientradio")
        self.gridLayout_3.addWidget(self.orientradio, 1, 3, 1, 1)
        self.joystickbutton = QtWidgets.QPushButton(self.control_tab)
        self.joystickbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 255);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 255);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(200, 0, 200);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(200, 0, 200);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"              padding-left: 5px;\n"
"                padding-top: 5px;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.joystickbutton.setCheckable(True)
        self.joystickbutton.setObjectName("joystickbutton")
        self.gridLayout_3.addWidget(self.joystickbutton, 2, 0, 1, 4)
        self.acousticfreqlabel = QtWidgets.QLabel(self.control_tab)
        self.acousticfreqlabel.setObjectName("acousticfreqlabel")
        self.gridLayout_3.addWidget(self.acousticfreqlabel, 3, 0, 1, 4)
        self.acousticfreq_spinBox = QtWidgets.QSpinBox(self.control_tab)
        self.acousticfreq_spinBox.setMaximum(3000000)
        self.acousticfreq_spinBox.setObjectName("acousticfreq_spinBox")
        self.gridLayout_3.addWidget(self.acousticfreq_spinBox, 4, 0, 1, 4)
        self.applyacousticbutton = QtWidgets.QPushButton(self.control_tab)
        self.applyacousticbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(0, 0, 0);\n"
"                border-style: inset;\n"
"            }\n"
"\n"
"         QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(200, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"}")
        self.applyacousticbutton.setCheckable(True)
        self.applyacousticbutton.setObjectName("applyacousticbutton")
        self.gridLayout_3.addWidget(self.applyacousticbutton, 5, 0, 1, 3)
        self.led = QtWidgets.QLabel(self.control_tab)
        self.led.setStyleSheet("\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 12px;\n"
"                border-color: rgb(255, 0, 0);\n"
"         \n"
"                padding: 6px;")
        self.led.setText("")
        self.led.setObjectName("led")
        self.gridLayout_3.addWidget(self.led, 5, 3, 1, 1)
        self.memorylabel = QtWidgets.QLabel(self.control_tab)
        self.memorylabel.setObjectName("memorylabel")
        self.gridLayout_3.addWidget(self.memorylabel, 6, 0, 1, 1)
        self.memorybox = QtWidgets.QSpinBox(self.control_tab)
        self.memorybox.setMinimum(1)
        self.memorybox.setMaximum(100)
        self.memorybox.setProperty("value", 15)
        self.memorybox.setObjectName("memorybox")
        self.gridLayout_3.addWidget(self.memorybox, 6, 3, 1, 1)
        self.RRTtreesizelabel = QtWidgets.QLabel(self.control_tab)
        self.RRTtreesizelabel.setObjectName("RRTtreesizelabel")
        self.gridLayout_3.addWidget(self.RRTtreesizelabel, 7, 0, 1, 3)
        self.RRTtreesizebox = QtWidgets.QSpinBox(self.control_tab)
        self.RRTtreesizebox.setMinimum(1)
        self.RRTtreesizebox.setMaximum(100)
        self.RRTtreesizebox.setProperty("value", 25)
        self.RRTtreesizebox.setObjectName("RRTtreesizebox")
        self.gridLayout_3.addWidget(self.RRTtreesizebox, 7, 3, 1, 1)
        self.arrivalthreshlabel = QtWidgets.QLabel(self.control_tab)
        self.arrivalthreshlabel.setObjectName("arrivalthreshlabel")
        self.gridLayout_3.addWidget(self.arrivalthreshlabel, 8, 0, 1, 3)
        self.arrivalthreshbox = QtWidgets.QSpinBox(self.control_tab)
        self.arrivalthreshbox.setMinimum(1)
        self.arrivalthreshbox.setMaximum(100)
        self.arrivalthreshbox.setProperty("value", 20)
        self.arrivalthreshbox.setObjectName("arrivalthreshbox")
        self.gridLayout_3.addWidget(self.arrivalthreshbox, 8, 3, 1, 1)
        self.rollingfrequencylabel = QtWidgets.QLabel(self.control_tab)
        self.rollingfrequencylabel.setObjectName("rollingfrequencylabel")
        self.gridLayout_3.addWidget(self.rollingfrequencylabel, 9, 0, 1, 2)
        self.rollingfrequencybox = QtWidgets.QSpinBox(self.control_tab)
        self.rollingfrequencybox.setMinimum(0)
        self.rollingfrequencybox.setMaximum(40)
        self.rollingfrequencybox.setProperty("value", 10)
        self.rollingfrequencybox.setObjectName("rollingfrequencybox")
        self.gridLayout_3.addWidget(self.rollingfrequencybox, 9, 3, 1, 1)
        self.psidial = QtWidgets.QDial(self.control_tab)
        self.psidial.setStyleSheet("QDial\n"
"    {\n"
"        background-color:QLinearGradient( \n"
"            x1: 0.177, y1: 0.004, x2: 0.831, y2: 0.911, \n"
"            stop: 0 white, \n"
"            stop: 0.061 white, \n"
"            stop: 0.066 lightgray, \n"
"            stop: 0.5 #242424, \n"
"            stop: 0.505 #000000,\n"
"            stop: 0.827 #040404,\n"
"            stop: 0.966 #292929,\n"
"            stop: 0.983 #2e2e2e\n"
"        );\n"
"    }")
        self.psidial.setMinimum(1)
        self.psidial.setMaximum(90)
        self.psidial.setSingleStep(5)
        self.psidial.setProperty("value", 90)
        self.psidial.setNotchTarget(10.0)
        self.psidial.setNotchesVisible(True)
        self.psidial.setObjectName("psidial")
        self.gridLayout_3.addWidget(self.psidial, 10, 0, 1, 2)
        self.gammadial = QtWidgets.QDial(self.control_tab)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.gammadial.setFont(font)
        self.gammadial.setStyleSheet("QDial {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0 #1a5276, stop:0.3 #2980b9, stop:0.7 #3498db, stop:1 #1a5276);\n"
"    border: 2px solid #1a5276;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDial::handle {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0 #f39c12, stop:0.3 #f1c40f, stop:0.7 #f39c12, stop:1 #f1c40f);\n"
"    border: 2px solid #e67e22;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    margin: -5px;\n"
"}\n"
"")
        self.gammadial.setMaximum(180)
        self.gammadial.setSingleStep(5)
        self.gammadial.setPageStep(10)
        self.gammadial.setProperty("value", 90)
        self.gammadial.setOrientation(QtCore.Qt.Horizontal)
        self.gammadial.setWrapping(False)
        self.gammadial.setNotchTarget(10.0)
        self.gammadial.setNotchesVisible(True)
        self.gammadial.setObjectName("gammadial")
        self.gridLayout_3.addWidget(self.gammadial, 10, 2, 1, 2)
        self.psilabel = QtWidgets.QLabel(self.control_tab)
        self.psilabel.setObjectName("psilabel")
        self.gridLayout_3.addWidget(self.psilabel, 11, 0, 1, 2)
        self.gammalabel = QtWidgets.QLabel(self.control_tab)
        self.gammalabel.setObjectName("gammalabel")
        self.gridLayout_3.addWidget(self.gammalabel, 11, 2, 1, 2)
        self.magneticfieldsimlabel = QtWidgets.QLabel(self.control_tab)
        self.magneticfieldsimlabel.setMinimumSize(QtCore.QSize(200, 200))
        self.magneticfieldsimlabel.setStyleSheet("background-color: rgb(0,0,0); border:2px solid rgb(255, 0, 0); ")
        self.magneticfieldsimlabel.setText("")
        self.magneticfieldsimlabel.setObjectName("magneticfieldsimlabel")
        self.gridLayout_3.addWidget(self.magneticfieldsimlabel, 12, 0, 1, 4)
        self.simulationbutton = QtWidgets.QPushButton(self.control_tab)
        self.simulationbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 255, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 100, 0);\n"
"                min-width: 1em;\n"
"                padding: 2px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 100, 0);\n"
"                border-style: inset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.simulationbutton.setCheckable(True)
        self.simulationbutton.setObjectName("simulationbutton")
        self.gridLayout_3.addWidget(self.simulationbutton, 13, 0, 1, 4)
        self.tabWidget.addTab(self.control_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actiondock = QtWidgets.QAction(MainWindow)
        self.actiondock.setMenuRole(QtWidgets.QAction.NoRole)
        self.actiondock.setObjectName("actiondock")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frameslider.setFormat(_translate("MainWindow", "Frame %v"))
        self.choosevideobutton.setText(_translate("MainWindow", "Choose Video"))
        self.trackbutton.setText(_translate("MainWindow", "Track"))
        self.framelabel.setText(_translate("MainWindow", "Frame: "))
        self.pausebutton.setText(_translate("MainWindow", "Pause"))
        self.leftbutton.setText(_translate("MainWindow", "..."))
        self.rightbutton.setText(_translate("MainWindow", "..."))
        self.maskbutton.setText(_translate("MainWindow", "Mask"))
        self.maskinvert_checkBox.setText(_translate("MainWindow", "Invert Mask: True"))
        self.maskthreshlabel.setText(_translate("MainWindow", "Mask Thresh"))
        self.maskdilationlabel.setText(_translate("MainWindow", "Mask Dilation"))
        self.croplengthlabel.setText(_translate("MainWindow", "Crop Length"))
        self.savedatabutton.setText(_translate("MainWindow", "Save Data"))
        self.recordbutton.setText(_translate("MainWindow", "Record"))
        self.robotarealabel.setText(_translate("MainWindow", "Area:"))
        self.robotvelocitylabel.setText(_translate("MainWindow", "Velocity:"))
        self.robotblurlabel.setText(_translate("MainWindow", "Blur:"))
        self.resetdefaultbutton.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tracking_tab), _translate("MainWindow", "Tracking"))
        self.controlbutton.setText(_translate("MainWindow", "Control"))
        self.rollradio.setText(_translate("MainWindow", "Roll"))
        self.swimradio.setText(_translate("MainWindow", "Swim"))
        self.orientradio.setText(_translate("MainWindow", "Orient"))
        self.joystickbutton.setText(_translate("MainWindow", "Joystick"))
        self.acousticfreqlabel.setText(_translate("MainWindow", "Acoustic Frequency"))
        self.applyacousticbutton.setText(_translate("MainWindow", "Apply"))
        self.memorylabel.setText(_translate("MainWindow", "Memory"))
        self.RRTtreesizelabel.setText(_translate("MainWindow", "RRT Tree Size"))
        self.arrivalthreshlabel.setText(_translate("MainWindow", "Arrive Thresh"))
        self.rollingfrequencylabel.setText(_translate("MainWindow", "Frequency"))
        self.psilabel.setText(_translate("MainWindow", "Psi: 90"))
        self.gammalabel.setText(_translate("MainWindow", "Gamma: 90"))
        self.simulationbutton.setText(_translate("MainWindow", "Simulation On"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_tab), _translate("MainWindow", "Control"))
        self.actiondock.setText(_translate("MainWindow", "dock"))
